### PR TITLE
Add logic to verify if git is present and git version meets requirements 

### PR DESCRIPTION
**Pull request by Binary-Eater**
Now that support for various authentication schemes is available in git
2.46, add explicit version checking in the credential helper program to
prevent incorrect usage in an invalid setup.

### Example of the guarding logic

```
❯ git pull
Found git version 2.44.1. git>=2.46 is required to use git-credential-msal.
Username for 'XXXXXXXXXX': 
```

### Example of program working with git 2.47

```
❯ git pull
remote: Enumerating objects: 6742, done.
remote: Counting objects: 100% (6742/6742), done.
remote: Compressing objects: 100% (3063/3063), done.
remote: Total 6742 (delta 3559), reused 6507 (delta 3466), pack-reused 0 (from 0)
Receiving objects: 100% (6742/6742), 2.34 MiB | 3.14 MiB/s, done.
Resolving deltas: 100% (3559/3559), completed with 22 local objects.
....
```

### CODE REVIEW

**Comment by aaronp24** [comment]
The cleanup and README changes seem fine, but is the version check really needed? The credential helper already checks for `authtype` in the capability list and skips doing anything if it's missing. Maybe we can just assume that it's git<2.46 if the `capability` field is missing?

**Comment by Binary-Eater** [comment]
Hmmm, the reason I was inspired to do this was because a user had no idea what was wrong when trying to use the program. Maybe I should just add the print logic in the authtype check?

**Comment by Binary-Eater** [comment]
Yeah, I think I will only do the min version checking **if** the authtype field is missing. Does that seem reasonable? That way, the utility will not guard against custom backporting of the needed support.

**Comment by aaronp24** [comment]
I'm fine with either way. Adding a dependency on a new Python package seems unfortunate but not horrible. I also think just something like
```
if (authtype is missing)
  print "Your version of git doesn't support the `authtype` credential field."
  print "Please make sure git version 2.46 or newer is installed."
```
would be fine.

**Comment by Binary-Eater** [comment]
Ah, I see. I agree about the dependency part, so I will just add a message for the `authtype` check.

**Comment by Binary-Eater** [comment]
@aaronp24 any opinions?

**Review by aaronp24 — APPROVED** [review]

**Pull request merged**
